import Container from './components/Container/Container'
import SideBar from './components/Header/SideBar'
import './globals.css'
import { Poppins } from 'next/font/google'

const poppins = Poppins({ 
  weight: ['200','400','600','800'],
  subsets: ['latin'],
 })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <SideBar />
        <main id='main_Wrap' className='pl-20 pt-16'>
          <Container>
            {children}
          </Container>
        </main>
      </body>
    </html>
  )
}
